// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {app} from '../models';

export function Add(arg1:config.Definition):Promise<void>;

export function ListenOn(arg1:string):Promise<void>;

export function Products():Promise<Array<app.Product>>;

export function Remove(arg1:string):Promise<void>;

export function Snapshot():Promise<app.View>;

export function Update(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;
