// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['app']['App']['Add'](arg1);
}

export function ListenOn(arg1) {
  return window['go']['app']['App']['ListenOn'](arg1);
}

export function Products() {
  return window['go']['app']['App']['Products']();
}

export function Remove(arg1) {
  return window['go']['app']['App']['Remove'](arg1);
}

export function RequestLANAccess() {
  return window['go']['app']['App']['RequestLANAccess']();
}

export function Snapshot() {
  return window['go']['app']['App']['Snapshot']();
}

export function Update(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Update'](arg1, arg2, arg3, arg4);
}
